In [709]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import GridSearchCV, KFold
import sklearn.svm as svm
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import os

In [710]:
file_path = '/Users/juyeonpark/Desktop/titactoedatasets/tictactoedatasets/tictac_final.txt'
print('File exists:', os.path.exists(file_path))

np.arr = np.loadtxt(file_path)

X = np.arr[:, :9 ]
Y = np.arr[:, 9:]

print(X.shape)
print(Y.shape)

File exists: True
(958, 9)
(958, 1)


In [711]:
file_path2 = '/Users/juyeonpark/Desktop/titactoedatasets/tictactoedatasets/tictac_single.txt'
print('File exists:', os.path.exists(file_path2))

np.arr2 = np.loadtxt(file_path2)

X2 = np.arr2[:, : 9 ]
Y2 = np.arr2[:, 9:]

print(X2.shape)
print(Y2.shape)

File exists: True
(6551, 9)
(6551, 1)


In [712]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.7)
print ("from tictac_final.txt:")
print (x_train.shape, y_train.shape)
print (x_test.shape, y_test.shape)

from tictac_final.txt:
(287, 9) (287, 1)
(671, 9) (671, 1)


In [713]:
x2_train, x2_test, y2_train, y2_test = train_test_split(X2, Y2, test_size = 0.7)
print ("from tictac_single.txt:")
print (x2_train.shape, y2_train.shape)
print (x2_test.shape, y2_test.shape)

from tictac_single.txt:
(1965, 9) (1965, 1)
(4586, 9) (4586, 1)


In [714]:
def _init_SVC_Reg():
    
    kfd = KFold(n_splits = 20, shuffle=True, random_state = 10)
    param_setting ={
        'C': [0.01,0.1,1,2,5]
    }
    
    svc = svm.SVC(kernel='linear')
    
    init_reg = LinearRegression()
    
    clf = GridSearchCV(svc, param_setting, cv=kfd)
    reg = GridSearchCV(init_reg, param_setting, cv=kfd)
    
    return clf

In [715]:
def SVC_Classifier(x_train,y_train, x_test, y_test):

    clf = _init_SVC_Reg()
    clf.fit(x_train,y_train)
    
    best_score = clf.best_score_
    best_params = clf.best_params_
    y_pred = clf.predict(x_test)
    
    print('the best score is: ')
    print(best_score)
    
    print('the best parameter is: ')
    print(best_params)
    
    test_acc = accuracy_score(y_test, y_pred)
    print('Test accuracy:', test_acc)
    
    cm = confusion_matrix(y_test, y_pred)
    print("Confusion Matrix is: ")
    print(cm)
    

In [716]:
print('final dataset: ')
SVC_Classifier(x_train,y_train, x_test, y_test)
print('single dataset: ')
SVC_Classifier(x2_train,y2_train, x2_test, y2_test)

final dataset: 


/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected

the best score is: 
0.9828571428571429
the best parameter is: 
{'C': 1}
Test accuracy: 0.9836065573770492
Confusion Matrix is: 
[[222  11]
 [  0 438]]
single dataset: 


/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected

the best score is: 
0.3633271490414348
the best parameter is: 
{'C': 5}
Test accuracy: 0.3554295682511993
Confusion Matrix is: 
[[1098    0    0    0    0    0    0    0    0]
 [ 301  245    0    0   38    0    0    0    0]
 [ 380   93  168    0   45    0    0    0    0]
 [ 199   63   33   15   39    0    2    0    0]
 [ 440  139   68    0   99    0    0    0    0]
 [ 141   47   39    5   17    0    0    0    0]
 [ 228   73   35    0   26    0    1    0    0]
 [ 121   46   10    0    7    0    4    4    0]
 [ 190   82   37    3    5    0    0    0    0]]


In [719]:
from sklearn.metrics import mean_squared_error
def Linear_Regressor(x_train,y_train, x_test, y_test):
    
    reg = _init_SVC_Reg()
    reg.fit(x_train,y_train)

    best_score = reg.best_score_
    best_params = reg.best_params_
    best_esti = reg.best_estimator_
    
    y_pred = reg.predict(x_test)
    #y_pred = np.where(y_pred > 0.5,1, 0)
    
    test_acc = accuracy_score(y_test, y_pred)
    print('Test accuracy:', test_acc)
    
    mse = mean_squared_error(y_test,y_pred,squared=False)
    print('mean squared error: ',mse)
    print('the best score: ')
    print(best_score)
    
    print('the best parameter is: ')
    print(best_params)
    

In [720]:
print('final')
Linear_Regressor(x_train,y_train, x_test, y_test)
print('single')
Linear_Regressor(x2_train,y2_train, x2_test, y2_test)

final


/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected

Test accuracy: 0.9836065573770492
mean squared error:  0.25607375986579195
the best score: 
0.9828571428571429
the best parameter is: 
{'C': 1}
single


/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/Users/juyeonpark/opt/anaconda3/lib/python3.9/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected

Test accuracy: 0.3554295682511993
mean squared error:  3.4334048179173706
the best score: 
0.3633271490414348
the best parameter is: 
{'C': 5}
